
#FROM rabbitmq:management
# with ver on 20260228
FROM rabbitmq:4.2.4-management-alpine

COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf

COPY rabbit_last_2026-2-28.json /etc/rabbitmq/definitions.json
