CREATE TABLE [dbo].[Setting](
	[SettingID] [varchar](50) NOT NULL,
	[StrValue] [nvarchar](256) NULL,
 CONSTRAINT [PK_Setting] PRIMARY KEY NONCLUSTERED 
(
	[SettingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]