CREATE TABLE [crs].[OrdersLog] (
    [ReplId]                BIGINT          NULL,
    [ReplRev]               BIGINT          NULL,
    [ReplAct]               BIGINT          NULL,
    [PublicOrderId]       BIGINT          NULL,
    [SessionId]               INT             NULL,
    [IsinId]               INT             NULL,
    [PublicAmount]         BIGINT          NULL,
    [PublicAmountRest]    BIGINT          NULL,
    [DealId]               BIGINT          NULL,
    [XStatus]               BIGINT          NULL,
    [XStatus2]              BIGINT          NULL,
    [Price]                 DECIMAL (16, 5) NULL,
    [Moment]                DATETIME2 (3)   NULL,
    [MomentNs]             DECIMAL (20)    NULL,
    [Direction]                   TINYINT         NULL,
    [PublicAction]         TINYINT         NULL,
    [DealPrice]            DECIMAL (16, 5) NULL,
    [ClientCode]           NVARCHAR (7)    NULL,
    [LoginFrom]            NVARCHAR (20)   NULL,
    [Comment]               NVARCHAR (20)   NULL,
    [ExternalId]                INT             NULL,
    [BrokerTo]             NVARCHAR (7)    NULL,
    [BrokerToRts]         NVARCHAR (7)    NULL,
    [BrokerFromRts]       NVARCHAR (7)    NULL,
    [ExpirationDate]              DATETIME2 (3)   NULL,
    [OrderId1]               BIGINT          NULL,
    [AsPref]                INT             NULL,
    [PrivateOrderId]      BIGINT          NOT NULL,
    [PrivateAmount]        BIGINT          NULL,
    [PrivateAmountRest]   BIGINT          NULL,
    [VarianceAmount]       BIGINT          NULL,
    [DiscloseConstAmount] BIGINT          NULL,
    [PrivateAction]        TINYINT         NULL,
    [Reason]                INT             NULL,
    [MatchRef]             NVARCHAR (10)   NULL,
    [ComplianceId]         NVARCHAR (1)    NULL,

    PRIMARY KEY CLUSTERED ([PrivateOrderId] ASC)
);

