version: '3.4'
services:
  rabbit:
    build:
      context: ./images/Rabbit  
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped      
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - '5672:5672'
      - '15672:15672'
      
  mq.webservice:
    image: raulamailru/moexcgate-mq:0.0.2
    build:
      context: ./services/mq
      dockerfile: MQ.WebService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=8080
      #- ASPNETCORE_HTTPS_PORTS=8081
      - RabbitMQSettings__Host=${RABBIT_SERVER:-host.docker.internal}
      - ServiceWebMsgSettings__Workers__0__RabbitMQServSettings__Host=${RABBIT_SERVER:-host.docker.internal}
      - ServiceWebMsgSettings__Workers__1__RabbitMQServSettings__Host=${RABBIT_SERVER:-host.docker.internal}
      - ServiceWebMsgSettings__Workers__2__RabbitMQServSettings__Host=${RABBIT_SERVER:-host.docker.internal}
      - ServiceWebMsgSettings__Workers__0__DataBaseServSettings__ServerType=mssql 
      - ServiceWebMsgSettings__Workers__0__DataBaseServSettings__ServerName=${MQ_SERVER:-host.docker.internal}
      - ServiceWebMsgSettings__Workers__0__DataBaseServSettings__ClientName=${MQ_CLIENTNAME:-client1}
      - ServiceWebMsgSettings__Workers__0__DataBaseServSettings__DataBase=${MQ_DATABASE:-CGate}
      - ServiceWebMsgSettings__Workers__0__DataBaseServSettings__User=${MQ_USER:-postgres}
      - ServiceWebMsgSettings__Workers__0__DataBaseServSettings__Password=${MQ_PASSWORD:-postgres}
      - ServiceWebMsgSettings__Workers__1__DataBaseServSettings__ServerType=mssql 
      - ServiceWebMsgSettings__Workers__1__DataBaseServSettings__ServerName=${MQ_SERVER:-host.docker.internal}
      - ServiceWebMsgSettings__Workers__1__DataBaseServSettings__ClientName=${MQ_CLIENTNAME:-client1}
      - ServiceWebMsgSettings__Workers__1__DataBaseServSettings__DataBase=${MQ_DATABASE:-CGate}
      - ServiceWebMsgSettings__Workers__1__DataBaseServSettings__User=${MQ_USER:-postgres}
      - ServiceWebMsgSettings__Workers__1__DataBaseServSettings__Password=${MQ_PASSWORD:-postgres}
      - ServiceWebMsgSettings__Workers__2__DataBaseServSettings__ServerType=mssql 
      - ServiceWebMsgSettings__Workers__2__DataBaseServSettings__ServerName=${MQ_SERVER:-host.docker.internal}
      - ServiceWebMsgSettings__Workers__2__DataBaseServSettings__ClientName=${MQ_CLIENTNAME:-client1}
      - ServiceWebMsgSettings__Workers__2__DataBaseServSettings__DataBase=Log
      - ServiceWebMsgSettings__Workers__2__DataBaseServSettings__User=${MQ_USER:-postgres}
      - ServiceWebMsgSettings__Workers__2__DataBaseServSettings__Password=${MQ_PASSWORD:-postgres}
      - DataBaseSettings__ServerType=mssql 
      - DataBaseSettings__ServerName=${MQ_SERVER:-host.docker.internal}
      - DataBaseSettings__ClientName=${MQ_CLIENTNAME:-client1}
      - DataBaseSettings__DataBase=${MQ_DATABASE:-CGate}
      - DataBaseSettings__User=${MQ_USER:-postgres}
      - DataBaseSettings__Password=${MQ_PASSWORD:-postgres}
      - Serilog__MinimumLevel__Default=Debug
      #- Serilog__MinimumLevel__Default=Information
      #- Serilog__WriteTo__1__Args__formatter__template='[{@t:HH:mm:ss.ff}] [{@l:u3}] [{WorkerLogPrefix:3}] {@m}\n{NewLine}{@x}'
      #- Serilog__WriteTo__1__Args__formatter__template={Timestamp:yyyy-MM-dd HH:mm:ss} [{Level:u3}] {Message:lj}{NewLine}{Exception}
    ports:
      - "8090:8080"
      - "8091:8081"
    volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./logs:/logs   
    depends_on:
      rabbit:
        condition: service_healthy
        
  zipkin:
    image: ghcr.io/openzipkin/zipkin
    ports:
        # Port used for the Zipkin UI and HTTP Api
      - 9411:9411            

