version: '3.8'
services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cgatemssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=MyPassword321
    ports:
      - 1434:1433
    volumes:
      - ccgatemssql:/var/opt/mssql  
      - ./images/mssql/dacpac:/dacpac          
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P MyPassword321 -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s   

  mssql.configurator:
    image: ${DOCKER_REGISTRY-}mqmssql2022build
    #image: ://mcr.microsoft.com
    build:
      context: ./images/mssql
      dockerfile: Dockerfile    
    user: root
    volumes:
      - ./images/mssql/dacpac:/dacpac
    depends_on:
      mssql:
        condition: service_healthy
    command: >
      bash -c "
      sqlcmd -S mssql -U sa -P 'MyPassword321' -C -N o  -Q \"EXEC sp_configure 'show advanced options', 1; RECONFIGURE; EXEC sp_configure 'clr enabled', 1; EXEC sp_configure 'clr strict security', 0; RECONFIGURE;\";
      sqlcmd -S mssql -U sa -P 'MyPassword321' -C -N o  -Q \"IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'CGate') CREATE DATABASE CGate; ALTER DATABASE CGate SET TRUSTWORTHY ON;\";
      sqlcmd -S mssql -U sa -P 'MyPassword321' -C -N o  -Q \"IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'CGate') CREATE DATABASE Log; ALTER DATABASE Log SET TRUSTWORTHY ON;\";
      sqlcmd -S mssql -U sa -P 'MyPassword321' -C -N o  -Q \"ALTER AUTHORIZATION ON DATABASE::[CGate] TO [sa];\";
      HEX_CONTENT=$(od -An -v -t x1 /dacpac/RabbitMQ.Client.dll | tr -d ' \n');
      echo \"Registering RabbitMQ.Client assembly manually...\"
      sqlcmd -S mssql -U sa -P 'MyPassword321' -C -N o  -Q \"
        -- Если сборка уже есть (например, от неудачного деплоя), удаляем
        IF EXISTS (SELECT * FROM sys.assemblies WHERE name = 'RabbitMQ.Client') 
          DROP ASSEMBLY [RabbitMQ.Client];
    
        -- Создаем сборку из HEX-кода
        CREATE ASSEMBLY [RabbitMQ.Client] 
        FROM '/localdacpac/RabbitMQ.Client.dll'
        WITH PERMISSION_SET = SAFE;
      \";
      HEX_CONTENT=$(od -An -v -t x1 /dacpac/RabbitMQSqlClr4.dll | tr -d ' \n')      
      echo \"Registering RabbitMQ.Client assembly manually...\"
      sqlcmd -S mssql -U sa -P 'MyPassword321' -C -N o  -Q \"
        -- Если сборка уже есть (например, от неудачного деплоя), удаляем
        IF EXISTS (SELECT * FROM sys.assemblies WHERE name = 'RabbitMQSqlClr4') 
          DROP ASSEMBLY [RabbitMQSqlClr4];
    
        -- Создаем сборку из HEX-кода
        CREATE ASSEMBLY [RabbitMQSqlClr4] 
        FROM '/localdacpac/RabbitMQSqlClr4.dll'
        WITH PERMISSION_SET = SAFE;
      \"
      sqlpackage /a:Publish /tsn:mssql /TargetEncryptConnection:False /tdn:CGate /tu:sa /tp:MyPassword321 /sf:/dacpac/CGate.dacpac /v:LinkSRVLog=LinkSRVLog /p:AllowIncompatiblePlatform=True /p:IncludeCompositeObjects=True /p:IgnorePermissions=False;
      sqlpackage /a:Publish /tsn:mssql /TargetEncryptConnection:False /tdn:Log /tu:sa /tp:MyPassword321 /sf:/dacpac/Log.dacpac /v:LinkSRVLog=LinkSRVLogExt 
      "
    
volumes:
  ccgatemssql:
    driver: local


 

